[project]
name = "owlglass"
version = "0.1"
dependencies = ["requests"]

[build-system]
requires = ["setuptools>=75.8.0"]
build-backend = "setuptools.build_meta"

[project.scripts]
owlglass = "main:main"